version: '3.8'

services:
  backend:
    build:
      context: ./nodejs-express-sequelize-mysql-master
    ports:
      - "8089:8089"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./react-crud-web-api-master
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdatabase
    ports:
      - "3306:3306"
